version: "3.9"

services:

  tests:
    build: .
    command: pytest tests/ -v
    environment:
      ENV: test
      PIP_NO_INPUT: 1
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_CACHE_DIR: 1
    platform: linux/amd64
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
