name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Init process started at $(date)"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"
        working-directory: infrastructure/terraform

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: url-shortener-cluster
          location: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Wait for cluster
        run: |
          for i in {1..30}; do
            kubectl get nodes && break
            sleep 10
          done

      - name: Debug cluster
        run: |
          kubectl config current-context
          kubectl get nodes
          kubectl get ns

      - name: Deploy App & Monitoring
        env:
          GRAFANA_USER: ${{ secrets.GRAFANA_ADMIN_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          kubectl create namespace url-shortener-ns --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

          # App
          kubectl apply -f infrastructure/k8s/deployment.yaml
          kubectl apply -f infrastructure/k8s/service.yaml

          # Monitoring
          kubectl apply -f infrastructure/k8s/monitoring/

          # Grafana secret
          kubectl create secret generic grafana-secrets \
            --namespace=monitoring \
            --from-literal=admin-user="$GRAFANA_USER" \
            --from-literal=admin-password="$GRAFANA_PASS" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Debug resources
        run: |
          kubectl get all -A
