name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Init process started at $(date)"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: url-shortener-cluster
          location: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy App & Monitoring
        env:
          GRAFANA_USER: ${{ secrets.GRAFANA_ADMIN_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        working-directory: .
        run: |
          echo "=== CREANDO NAMESPACES ==="
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

          echo "=== DESPLEGANDO APP ==="
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          echo "=== ESPERANDO EXTERNAL IP ==="
          kubectl get svc url-shortener-service -w

          echo "=== MONITORING ==="
          kubectl apply -f k8s/monitoring/

          echo "=== GRAFANA SECRET ==="
          kubectl create secret generic grafana-secrets \
            --namespace=monitoring \
            --from-literal=admin-user="$GRAFANA_USER" \
            --from-literal=admin-password="$GRAFANA_PASS" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Skip Terraform
        run: echo "Cluster already exists, skipping Terraform apply"
